{{- if .Values.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "consize.fullname" . }}-migrate
  namespace: {{ include "consize.namespace" . }}
  labels:
    {{- include "consize.componentLabels" (dict "root" . "component" "migrate") | nindent 4 }}
  {{- if .Values.migrate.useHelmHook }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  {{- end }}
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        {{- include "consize.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
      {{- with .Values.migrate.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . | quote }}
        {{- end }}
      {{- end }}
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          image: {{ include "consize.image" (list . "migrate") | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          env:
            {{- include "consize.databaseEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.migrate.resources | nindent 12 }}
{{- end }}
