{{- if and .Values.rbac.create .Values.rbac.writer.enabled }}
{{- range $namespace := .Values.rbac.writer.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "consize.fullname" $ }}-apply
  namespace: {{ $namespace }}
  labels:
    {{- include "consize.componentLabels" (dict "root" $ "component" "writer") | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "consize.fullname" $ }}-apply
  namespace: {{ $namespace }}
  labels:
    {{- include "consize.componentLabels" (dict "root" $ "component" "writer") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "consize.fullname" $ }}-apply
subjects:
  - kind: ServiceAccount
    name: {{ include "consize.writerServiceAccountName" $ }}
    namespace: {{ include "consize.namespace" $ }}
{{- end }}
{{- end }}
