{{- if .Values.serviceAccounts.reader.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "consize.readerServiceAccountName" . }}
  namespace: {{ include "consize.namespace" . }}
  labels:
    {{- include "consize.componentLabels" (dict "root" . "component" "reader") | nindent 4 }}
  {{- with .Values.serviceAccounts.reader.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.serviceAccounts.writer.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "consize.writerServiceAccountName" . }}
  namespace: {{ include "consize.namespace" . }}
  labels:
    {{- include "consize.componentLabels" (dict "root" . "component" "writer") | nindent 4 }}
  {{- with .Values.serviceAccounts.writer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
